language: node_js
addons:
  chrome: stable
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache
node_js: lts/*
notifications:
  email: false
install:
  - npm ci
script:
  - npm test -- --coverage --coverageReporters=text-lcov | node_modules/.bin/coveralls
  - npm run build
  - npm run start:serve
  - node_modules/.bin/cypress run --browser chrome --record --key $CYPRESS_RECORD_KEY
  - npm run stop:serve
after_success:
  - npx semantic-release
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/ # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
