language: node_js
cache:
  directories:
    - ~/.npm
node_js: lts/*
notifications:
  email: false
script:
  - npm run build
after_success:
  - npx semantic-release
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/ # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
